In [1]:
import numpy as np

In [25]:
a = np.arange(1,13)

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
a.ndim

1

In [52]:
a = a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
np.insert(a,[0,1,2,3,2],[0,1,2,3], axis = 0)

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 9, 10, 11, 12],
       [ 0,  1,  2,  3]])

In [58]:
type(a)

numpy.ndarray

In [59]:
a.ndim

2

In [60]:
import sys

In [61]:
sys.getsizeof(a)

128

In [75]:
ar = np.array([])

In [76]:
ar

array([], dtype=float64)

In [77]:
sys.getsizeof(ar)

112

In [78]:
l = []

In [79]:
sys.getsizeof(l)

56

In [80]:
l = [1]

In [81]:
sys.getsizeof(l)

64

In [94]:
ar = np.array([1],dtype='int8')

In [95]:
sys.getsizeof(ar)

113

In [96]:
ar.dtype

dtype('int8')

In [134]:
#a = np.arange(1000000000, dtype='int8')

In [135]:
sys.getsizeof(a)

10000000112

In [ ]:
#l = list(range(1000000000))

In [137]:
sys.getsizeof(l)

8056

In [138]:
%time for i in a:pass

KeyboardInterrupt: 

In [133]:
%time for i in l:pass

CPU times: total: 0 ns
Wall time: 0 ns
